### ISSUE TITLE
进阶教程-调用服务，示例代码错误

### ISSUE THREAD

**Issue by samuelyao314** [cloudwego/cloudwego.github.io#1036]
例子里没找到 api.Request ，应该是item.GetItemReq 才对

```go
	req := &item.GetItemReq{}
	resp, err := c.GetItem(context.Background(), req, callopt.WithRPCTimeout(3*time.Second))
	if err != nil {
		log.Fatal(err)
	}

```

**Comment by rogerogers** [comment]
感谢反馈，https://github.com/cloudwego/kitex-examples/blob/ac2581cb444e88e1008b62b4eb40a9ff72373bf2/basic/example_shop/api/main.go#L56 看了下示例代码对应这个位置

**Comment by rogerogers** [comment]
是有问题的，方便 pr 修复下吗
