### ISSUE TITLE
go get github.com/hertz-contrib/pprof

### ISSUE THREAD

**Issue by pnf838298** [cloudwego/cloudwego.github.io#1049]
执行go get github.com/hertz-contrib/pprof 提示
go: module github.com/hertz-contrib/pprof: reading https://goproxy.cn/github.com/hertz-contrib/pprof/@v/list: 504 Gateway Timeout

**Comment by rogerogers** [comment]
https://status.goproxy.cn/

他们网站有问题
可以关注下 status 页面，或者换一个代理
比如 https://developer.aliyun.com/mirror/goproxy
