### ISSUE TITLE
Import "openapiv3/annotations.proto" was not found or had errors.

### ISSUE THREAD

**Issue by xuyang404** [cloudwego/cloudwego.github.io#1063]
hz new -I=idl --idl=idl/hello/hello.proto --protoc-plugins=openapi::./docs --mod=middleware/hertz

报错：
plugin protoc_gen_hertz returns error: exit status 1, cause:
openapiv3/annotations.proto: File not found.
google/api/annotations.proto: File not found.
hello.proto:8:1: Import "openapiv3/annotations.proto" was not found or had errors.
hello.proto:9:1: Import "google/api/annotations.proto" was not found or had errors.

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/hertz-examples/issues/143
