### ISSUE TITLE
SetCustomSignalWaiter

### ISSUE THREAD

**Issue by shichaosc** [cloudwego/cloudwego.github.io#1065]
倾斜一个简单的demo来展示SetCustomSignalWaiter跟signal怎么结合使用

**Comment by li-jin-gou** [comment]
你看看默认的实现是不是就可以写了



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 28, 2024 18:14 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [cloudwego/cloudwego.github.io] SetCustomSignalWaiter (Issue #1065)




 
倾斜一个简单的demo来展示SetCustomSignalWaiter跟signal怎么结合使用

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/hertz/blob/develop/pkg/app/server/hertz.go#L97
