### ISSUE TITLE
文档代码区阅读很不方便

### ISSUE THREAD

**Issue by LF-DevJourney** [cloudwego/cloudwego.github.io#1071]
1. 不会自动折行，需要拉水平滚动条来回看。
2. 代码区高度超过屏幕高度时，阅读上面的部分时，水平滚动条在屏幕外，需要先滚动到最下，然后拖水平滚动条，然后再回到顶部查看。

这种操作十分不方便。
![图片](https://github.com/cloudwego/cloudwego.github.io/assets/26386181/234800bc-b765-4f7b-ab73-d607fc51a24f)

**Comment by GuangmingLuo** [comment]
这是树状图展示结构，没法换行，换行树状图就乱了。
关于 1， 用 Mac 操作体验会好一些；关于2，可以在大一点的屏幕上查看。

**Comment by LF-DevJourney** [comment]
嗯，先这样看了
