### ISSUE TITLE
基于PB的泛化调用方式只能基于本地proto文件

### ISSUE THREAD

**Issue by stevenhoukai** [cloudwego/cloudwego.github.io#1076]
目前基于PB的泛化调用好像没有支持内存解析IDL内容的哈，只支持基于本地文件解析IDL的方式，可否也提供支持一下基于内存解析IDL内容的方式哈，这样才能真正做到hertz实现Api-Gateway的动态服务发现

**Comment by AsterDY** [comment]
Yes. 我们后续补充一下吧

**Comment by AsterDY** [comment]
fixed by https://github.com/cloudwego/kitex/pull/1359
