### ISSUE TITLE
单 Server 多 Service

### ISSUE THREAD

**Issue by zhaoliubox** [cloudwego/cloudwego.github.io#1085]
单 Server 多 Service怎么注册到etcd

`	svr := server.NewServer(server.WithRegistry(etcd),
		server.WithServiceAddr(addr),
		server.WithServerBasicInfo(&rpcinfo.EndpointBasicInfo{ServiceName: "main.user.xxx"}))

	err := login.RegisterService(svr, new(userApi.UserLoginServiceImpl))
	if err != nil {
		klog.Error(err)
		return
	}
	err = status.RegisterService(svr, new(statusApi.UserStatusServiceImpl))
	if err != nil {
		klog.Error(err)
		return
	}

	err = svr.Run()
`

**Comment by Marina-Sakai** [comment]
@zhaoliubox Doesn't `server.WithRegistry(etcd)` work? Or do you want to register a different etcd for each service?
