### ISSUE TITLE
文档示例中（ ctx *app.Requestcontext）的名称风格不一致

### ISSUE THREAD

**Issue by Anxiangchegu** [cloudwego/cloudwego.github.io#1111]
*** Hertz文档（http://cloudwego.cn/zh/docs/hertz） 代码示例中关于 ctx *app.Requestcontext的命名风格不一致，如下图所示。
<img width="880" alt="e22cfcad4f2a8fa58b3ff1e4703fe41" src="https://github.com/user-attachments/assets/55d2205a-08bc-465e-ba1e-91989e4c8270">
<img width="970" alt="ee678cc58ad067246d503ebc434264c" src="https://github.com/user-attachments/assets/41478802-fee2-4599-8d98-400a6cfd806d">

**Comment by GuangmingLuo** [comment]
@Skyenought PLZ help to fix, thanks

**Comment by GuangmingLuo** [comment]
感谢反馈，这个问题已经修复啦 @Anxiangchegu
