### ISSUE TITLE
1.在当前目录下创建 hertz_demo 文件夹。“当前目录”具体是哪个目录？

### ISSUE THREAD

**Issue by zhangxiaoliu** [cloudwego/cloudwego.github.io#1116]
**快速上手**
在完成环境准备后，可以按照如下操作快速启动 Hertz Server：

1.在当前目录下创建 hertz_demo 文件夹，进入该目录中。

“当前目录”具体是哪个目录？

**Comment by GuangmingLuo** [comment]
快速开始里面，当前目录就是任意工作目录
