### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by javasopp** [cloudwego/cloudwego.github.io#1137]
在这个[页面](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/recovery/)中,这一行示例代码:
`hlog.SystemLogger().CtxErrorf(c, "[Recovery] err=%v\nstack=%s", err, stack)`
应更改为
`hlog.SystemLogger().CtxErrorf(ctx, "[Recovery] err=%v\nstack=%s", err, stack)`

**Comment by GuangmingLuo** [comment]
页面右侧有个直接修改的按钮，请直接修改提交pr吧
