### ISSUE TITLE
install hertz/cmd/hz 遇到问题

### ISSUE THREAD

**Issue by xieyj-apple** [cloudwego/cloudwego.github.io#1172]
go install github.com/cloudwego/hertz/cmd/hz@latest 

go: github.com/cloudwego/hertz/cmd/hz@latest : module github.com/cloudwego/hertz@latest found (v0.9.1), but does not contain package github.com/cloudwego/hertz/cmd/hz

**Comment by GuangmingLuo** [comment]
@xiaost please take a look

**Comment by xiaost** [comment]
This is the repo for website.

Please report a bug to [cloudwego/hertz](https://github.com/cloudwego/hertz) repo via the link below with information required by the template. 

https://github.com/cloudwego/hertz/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
