### ISSUE TITLE
RPC 框架 Kitex 实践入门：性能测试指南

### ISSUE THREAD

**Issue by baiyutang** [cloudwego/cloudwego.github.io#134]
```
每类连接模型没有绝对好坏，取决于实际使用场景。连接多路复用虽然一般来说性能相对最好，但应用上必须依赖协议能够支持包序列号，且一些老框架服务可能也并不支持多路复用的方式调用。
```

[这句话](https://www.cloudwego.io/zh/blog/2021/11/24/rpc-%E6%A1%86%E6%9E%B6-kitex-%E5%AE%9E%E8%B7%B5%E5%85%A5%E9%97%A8%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95%E6%8C%87%E5%8D%97/)里有一处不明白，是“能够支持包序列号”，还是想表达“序列化”？

**Comment by lsjbd** [comment]
> “能够支持包序列号

是指协议需要有字段能够标记当前发送的包的「序列号」，例如 thrift 协议里 message 都有的 sequence ID。连接多路复用要求同一个连接上的所有请求都应该有唯一的序列号以示区分。

**Comment by joway** [comment]
@baiyutang 我们以 HTTP 协议举例：

```
GET /mypage.html HTTP/1.0
User-Agent: NCSA_Mosaic/2.0 (Windows 3.1)
```

在 http 1.1 之前都是类似上面这样的文本协议格式，在 1.0 的时候必须一个请求对应一个返回。如果一个连接同时发送两个 request 1,2，你收到的 response 属于哪个请求的返回就搞不清楚了。1.1 做的改进是允许顺序发送，顺序返回。总之目的其实就是分得清楚哪个返回属于哪个请求。

所以 http 2 就加了一个叫 stream id 的东西：
![image](https://user-images.githubusercontent.com/8353464/152719880-72c30268-9cef-42ce-9fc8-2e321e2332d8.png)

其他支持连接多路复用的协议也大致是类似的做法。
