### ISSUE TITLE
request: documentation about ByteAPI IDL specification

### ISSUE THREAD

**Issue by lsjbd** [cloudwego/cloudwego.github.io#141]
Missing links in generic documents:

* https://www.cloudwego.io/zh/docs/kitex/tutorials/advanced-feature/generic_call/#2-http-映射泛化调用
* https://www.cloudwego.io/docs/kitex/tutorials/advanced-feature/generic_call/#2-http-mapping-generic-call

**Comment by GuangmingLuo** [comment]
Updated: https://www.cloudwego.io/docs/kitex/tutorials/advanced-feature/generic-call/

[IDL Definition Specification for Mapping between Thrift and HTTP](https://www.cloudwego.io/docs/kitex/tutorials/advanced-feature/generic-call/thrift_idl_annotation_standards)
