### ISSUE TITLE
找不到 github.com/kitex-contrib/opentracing

### ISSUE THREAD

**Issue by dierbei** [cloudwego/cloudwego.github.io#143]
![image](https://user-images.githubusercontent.com/52097565/157161734-dff1b3e0-ec99-42f7-810f-cbeec2e8e35f.png)

**Comment by GuangmingLuo** [comment]
The correct repo is : https://github.com/kitex-contrib/tracer-opentracing

Please raise an issue in this repo: https://github.com/cloudwego/kitex-examples
