### ISSUE TITLE
编解码协议

### ISSUE THREAD

**Issue by EddieChan1993** [cloudwego/cloudwego.github.io#145]
kitex -type thrift ${service_name} ${idl_name}.thrift
这里这种格式，提示如下。实际我是存在该文件的
```
Require exactly 1 IDL file.
```

**Comment by YangruiEmma** [comment]
`kitex -type thrift -service ${service_name} ${idl_name}.thrift` 需要通过-service指定 service name

**Comment by EddieChan1993** [comment]
> `kitex -type thrift -service ${service_name} ${idl_name}.thrift` 需要通过-service指定 service name

-service 这种，我看文档描述是生成服务端相关代码，上面我提出的问题，实际是看文档描述的是生成客户端代码，但是我试了试发现有问题

**Comment by YangruiEmma** [comment]
> > `kitex -type thrift -service ${service_name} ${idl_name}.thrift` 需要通过-service指定 service name
> 
> -service 这种，我看文档描述是生成服务端相关代码，上面我提出的问题，实际是看文档描述的是生成客户端代码，但是我试了试发现有问题

请问是哪个文档麻烦发下，如果只是客户端的话，thrift 直接 `kitex ${idl_name}.thrift`

**Comment by GuangmingLuo** [comment]
Close due to no reply.
