### ISSUE TITLE
Please add FAQ about kitex template and generator parameters

### ISSUE THREAD

**Issue by Skyenought** [cloudwego/cloudwego.github.io#194]
Please add FAQ about kitex template and generator parameters.
1. Why user defined templates are not supported ？
2. Why is it not supported to automatically resolve IDL's suffixes and directly read go Module information in _go.mod_

**Comment by GuangmingLuo** [comment]
Solved：
1. https://github.com/cloudwego/cloudwego.github.io/pull/197
2. https://github.com/cloudwego/cloudwego.github.io/pull/199
