### ISSUE TITLE
Hertz lack of service discovery based on the Overview doc

### ISSUE THREAD

**Issue by windard** [cloudwego/cloudwego.github.io#220]
架构设计右上角 Client 中的 `Service Discovery` 的部分还有么？没有找到相关代码
![](https://www.cloudwego.io/img/docs/hertz.png)

**Comment by Duslia** [comment]
hertz 的 server 和 client都支持中间件，这部分需求可以直接通过中间件的方式按需扩展（同时也是内部实现的方式）；这部分通用的能力暂时还在梳理当中，着急的话可以按照上述思路搞一版，有任何问题都欢迎在这里 https://github.com/cloudwego/hertz/issues/35 讨论~

**Comment by GuangmingLuo** [comment]
PR on the way: https://github.com/cloudwego/hertz/pull/133

**Comment by GuangmingLuo** [comment]
Check this for doc: https://www.cloudwego.io/zh/docs/hertz/tutorials/service-governance/service_discovery/
