### ISSUE TITLE
hz 命令行工具使用

### ISSUE THREAD

**Issue by loenvom** [cloudwego/cloudwego.github.io#296]
在使用 hz 工具的时候需要指定 thrift 的依赖版本为 v0.13.0，使用官网写的最新版本会出现编译错误。
<img width="706" alt="image" src="https://user-images.githubusercontent.com/59039948/183983724-8a1f2f08-d85e-4ecf-9473-351112d2a8b3.png">

**Comment by FGYFFFF** [comment]
生成的代码的时候已经默认在go.mod中加了 replace 到 thrift v0.13.0 的命令。你具体的使用姿势是啥呀？另外如果不想引用thrift的依赖，可以指定"--thriftgo=template=slim"。
hz的问题最好到[hertz](https://github.com/cloudwego/hertz/issues)提issue

**Comment by loenvom** [comment]
看起来是我用hz生成的 go.mod 里没有对应的replace命令，在文档里的这个指令让我误以为go.mod依赖的thrift也是最新的，所以提了这个issue，但是看起来并不是问题，算是我踩了坑，哈哈哈
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/59039948/184076283-14ac447c-00b4-42ce-9a8e-203d817a9787.png">

**Comment by FGYFFFF** [comment]
> 看起来是我用hz生成的 go.mod 里没有对应的replace命令，在文档里的这个指令让我误以为go.mod依赖的thrift也是最新的，所以提了这个issue，但是看起来并不是问题，算是我踩了坑，哈哈哈 <img alt="image" width="1006" src="https://user-images.githubusercontent.com/59039948/184076283-14ac447c-00b4-42ce-9a8e-203d817a9787.png">

我很好奇，为啥你生成的代码没有replace?是用new建了空项目，然后update使用了thrift idl 吗？
