### ISSUE TITLE
:art: 请提供一个完整的客户端和服务端的代码案例

### ISSUE THREAD

**Issue by lomoye** [cloudwego/cloudwego.github.io#353]

**Comment by li-jin-gou** [comment]
具体说的是哪个项目呢....

**Comment by lomoye** [comment]
netpoll的，文档上好多省略号，跟着文档写不出一个server和client的案例出来

**Comment by li-jin-gou** [comment]
似乎在很早之前就提供了这样的代码案例: https://github.com/cloudwego/netpoll-examples
