### ISSUE TITLE
Not all trait items implemented, missing: `Response`, `Error`, `Future` [E0046]

### ISSUE THREAD

**Issue by fmnisme** [cloudwego/cloudwego.github.io#358]
Not all trait items implemented, missing: `Response`, `Error`, `Future` [E0046]

**Comment by li-jin-gou** [comment]
@fmnisme  You can describe it carefully, read it many times do not know what problem is being described...:slightly_frowning_face:

**Comment by GuangmingLuo** [comment]
I guess you mean something related to Volo ? Can you be more specific or at least add the corresponding link to the doc.
