### ISSUE TITLE
JSON Marshal 库

### ISSUE THREAD

**Issue by AND-YOU** [cloudwego/cloudwego.github.io#383]
Mac M1 上编译报错这一块里面的
设置GOARCH参数为amd64（即GOARCH=amd64）。请去除该参数或设置为 `arm64``这句话应该是有歧义吧，我是设置为arm64才成功，那前面那句话设置为amd64是不是有问题

**Comment by li-jin-gou** [comment]
感谢，这个和 Sonic 版本有关，我们完善一下文档。

**Comment by GuangmingLuo** [comment]
@AsterDY PTAL

**Comment by li-jin-gou** [comment]
cc @AsterDY
