### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by anqiansong** [cloudwego/cloudwego.github.io#42]
* [快速开始](https://www.cloudwego.io/zh/docs/getting-started/)页面中[使用](https://www.cloudwego.io/zh/docs/getting-started/#%E4%BD%BF%E7%94%A8)->【代码生成工具】链接无效
* 右侧菜单无效【编辑此页】、【添加子页面】、【提交文档问题】、【提交项目问题】
* [消息类型（message_type）](https://www.cloudwego.io/zh/docs/tutorials/basic-feature/message_type/)【补充】
    * TTHeader 链接无效

**Comment by GuangmingLuo** [comment]
Thanks for your feedback, we are fixing it.

**Comment by GuangmingLuo** [comment]
Fix link issues: https://github.com/cloudwego/cloudwego.github.io/pull/43
