### ISSUE TITLE
volo 文档不明确

### ISSUE THREAD

**Issue by qiuxiaori** [cloudwego/cloudwego.github.io#455]
没有一个通用的api文档吗？

**Comment by PureWhiteWu** [comment]
你好， docs.rs/volo  你看是你期望的通用的 API 文档嘛？

**Comment by qiuxiaori** [comment]
好吧 谢谢。 顺便问一下 ，怎样添加多个 .protp 模板呢 ，idl add 命令之后没有反应

**Comment by PureWhiteWu** [comment]
额，你具体执行的命令是啥呀？执行后的 volo.yml 文件内容是啥样的呀？
你看你方便的话，能不能加一下 Volo 的飞书用户群，我们详细来看看～

**Comment by GuangmingLuo** [comment]
close due to no response
