### ISSUE TITLE
路由

### ISSUE THREAD

**Issue by i-Yirannn** [cloudwego/cloudwego.github.io#472]
你好，对于通配路由中*path 的匹配情况：

路径 | 是否匹配
-- | --
/src/ | 匹配
/src/somefile.go | 匹配
/src/subdir/somefile.go | 不匹配

经过实际尝试，似乎第三种情况是会被匹配的，也就是通配路由可以跨越单个路径段。

不知道是不是我理解上有什么问题？

如果需要，我可以提供复现的代码和请求，不过只需要仿照上下文就可以了，subdir 多层也会被匹配

**Comment by li-jin-gou** [comment]
感谢反馈❤️，文档写的有问题，你愿意提交一个PR修复它嘛？

**Comment by EduFriendChen** [comment]
Please give it to me.
