### ISSUE TITLE
快速开始文档有误

### ISSUE THREAD

**Issue by mingz-wang** [cloudwego/cloudwego.github.io#476]
运行示例代码下的输出和上面示例代码对不上

输出部分文档如下：

> 如果不出意外，我们可以看到类似如下输出
> ```$ {"message":"pong"}```
> 到现在，我们已经成功启动了 Hertz Server，并完成了一次调用。

而上方示例代码如下：

```
func main() {
    h := server.Default()

    h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
            ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
    })

    h.Spin()
}
```

**Comment by Claude-Zq** [comment]
> 运行示例代码下的输出和上面示例代码对不上
> 
> 输出部分文档如下：
> 
> > 如果不出意外，我们可以看到类似如下输出
> > `$ {"message":"pong"}`
> > 到现在，我们已经成功启动了 Hertz Server，并完成了一次调用。
> 
> 而上方示例代码如下：
> 
> ```
> func main() {
>     h := server.Default()
> 
>     h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
>             ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
>     })
> 
>     h.Spin()
> }
> ```

能提供下你运行示例代码的输出吗

**Comment by Claude-Zq** [comment]
> 运行示例代码下的输出和上面示例代码对不上
> 
> 输出部分文档如下：
> 
> > 如果不出意外，我们可以看到类似如下输出
> > `$ {"message":"pong"}`
> > 到现在，我们已经成功启动了 Hertz Server，并完成了一次调用。
> 
> 而上方示例代码如下：
> 
> ```
> func main() {
>     h := server.Default()
> 
>     h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
>             ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
>     })
> 
>     h.Spin()
> }
> ```

能提供下你运行示例代码的输出吗

**Comment by li-jin-gou** [comment]
感谢反馈我们修复一下

**Comment by EduFriendChen** [comment]
Please give it to me.

**Comment by Claude-Zq** [comment]
> > > 运行示例代码下的输出和上面示例代码对不上
> > > 输出部分文档如下：
> > > > 如果不出意外，我们可以看到类似如下输出
> > > > `$ {"message":"pong"}`
> > > > 到现在，我们已经成功启动了 Hertz Server，并完成了一次调用。
> > > 
> > > 
> > > 而上方示例代码如下：
> > > ```
> > > func main() {
> > >     h := server.Default()
> > > 
> > >     h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
> > >             ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
> > >     })
> > > 
> > >     h.Spin()
> > > }
> > > ```
> > 
> > 
> > 能提供下你运行示例代码的输出吗
> 
> 是 Windows 示例代码中给的是 `{"ping": "pong"}` 所以运行出来也是这个，我后来在 Ubuntu 试了 `hz new` 方式给出的代码里面是 `{"message":"pong"}`
> 
> 复制 Windows示例代码 输出 如下 ![Snipaste_2022-12-16_10-49-06](https://user-images.githubusercontent.com/57054141/208010742-201bc486-e054-4c5e-8c26-87662ae7f9f7.jpg)
> 
> `hz new` 方式 输出如下 ![Snipaste_2022-12-16_10-52-35](https://user-images.githubusercontent.com/57054141/208011205-81901932-629f-4610-9240-603f9ff6b09a.jpg)
> 
> 所以只用改一下 Window示例代码就行了 ![Snipaste_2022-12-16_10-57-03](https://user-images.githubusercontent.com/57054141/208011756-fcb6d843-fd44-45c1-9d54-79d75219ad9c.jpg)

thx
