### ISSUE TITLE
日期格式如何传递，并解析为正确的格式，响应的日期如何格式化为yyyy-MM-dd HH:mm:ss

### ISSUE THREAD

**Issue by heroSoft205** [cloudwego/cloudwego.github.io#493]
象springboot有对应的@jsonFormat注解可以解决这样的问题，你们这个框架有吗？
还有 uint64 的数据 在java中应该是lang类型的吧，如果将lang类型json相应的时候，相应为string类型，否则，在浏览器段精度会缺失的。这些问题在你们的文档中没有体现。。。

**Comment by li-jin-gou** [comment]
Lack of key details, e.g. frameworks.

**Comment by li-jin-gou** [comment]
The description refers to the HTTP framework Hertz, which does not provide a jsonFormat annotation and requires you to customize the binding function refer to https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/binding-and-validate/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B%E8%A7%A3%E6%9E%90

**Comment by heroSoft205** [comment]
已经解决了
写了两篇文章记录
https://www.csdcb.cn/article/427.html
需要的可以看一下
https://www.csdcb.cn/article/hertzDateTime.html
