### ISSUE TITLE
代码示例

### ISSUE THREAD

**Issue by yupor5** [cloudwego/cloudwego.github.io#496]
[root@localhost super_faceimglocaloss]# ./faceimglocaloss 
panic: Unsupported CPU, maybe it's too old to run Sonic.

goroutine 1 [running]:
github.com/bytedance/sonic/internal/native.init.0()
	F:/golang/GOPATH/pkg/mod/github.com/bytedance/sonic@v1.3.5/internal/native/dispatch_amd64.go:144 +0x1fb

我这是虚拟机，cpu太旧了，，不能用，这是要我放弃了

**Comment by li-jin-gou** [comment]
使用的是 hertz 还是 sonic，如果是 hertz 的话可以使用条件编译，这样就可以不用 sonic 了。

**Comment by yupor5** [comment]
什么条件编译 如？

**Comment by yupor5** [comment]
自己改了下，好了，谢谢你的回复

**Comment by li-jin-gou** [comment]
> 自己改了下，好了，谢谢你的回复

看下 https://github.com/cloudwego/hertz/pull/278 这个哈
