### ISSUE TITLE
数据绑定，日期如何绑定，比如前端传递日期格式yyyy-MM-dd HH:mm:ss

### ISSUE THREAD

**Issue by heroSoft205** [cloudwego/cloudwego.github.io#497]
数据绑定，日期如何绑定，比如前端传递日期格式yyyy-MM-dd HH:mm:ss

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/binding-and-validate/#customize-type-resolution and you need to use customize-type-resolution.

**Comment by heroSoft205** [comment]
已经解决了
写了两篇文章记录
https://www.csdcb.cn/article/427.html
需要的可以看一下
https://www.csdcb.cn/article/hertzDateTime.html

**Comment by li-jin-gou** [comment]
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/binding-and-validate/  可以贡献到文章中以及 hertz-example

**Comment by heroSoft205** [comment]
回头我找个时间吧，加进来
