### ISSUE TITLE
NoRoute 与 NoMethod 使用 如何对register(h)生效

### ISSUE THREAD

**Issue by Corey-cloud** [cloudwego/cloudwego.github.io#499]
![image](https://user-images.githubusercontent.com/71750003/210199485-11b7422c-aba4-44de-a79d-0c093f227330.png)

![image](https://user-images.githubusercontent.com/71750003/210199466-aa9649c2-c0cb-4982-ba6d-1139efa3ff84.png)

NoRoute 与 NoMethod 使用 如何对register(h)生效

**Comment by Duslia** [comment]
请在 hertz 下面按照模板提 issue: https://github.com/cloudwego/hertz/issues

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/biz-demo/blob/main/easy_note/cmd/api/main.go#L41 and follow issue template in next time.
