### ISSUE TITLE
快速开始/安装代码生成工具中的问题

### ISSUE THREAD

**Issue by automano** [cloudwego/cloudwego.github.io#50]
针对第2步和第3步。

2. 安装 kitex：go get github.com/cloudwego/kitex/tool/cmd/kitex@latest
3. 安装 thriftgo：go get github.com/cloudwego/thriftgo@latest

会收到如下提示。

```
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

是否更换到用`go install`会更好？

**Comment by lsjbd** [comment]
嗯，go1.17 开始 `go get` 的语义调整了，文档发布时 go1.17 还没 release。感谢指出。
