### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Crer-lu** [cloudwego/cloudwego.github.io#511]
..\..\..\..\pkg\mod\github.com\cloudwego\hertz@v0.5.0\pkg\network\standard\connection.go:50:25: undefined: unix.EPIPE
..\..\..\..\pkg\mod\github.com\cloudwego\hertz@v0.5.0\pkg\network\standard\connection.go:50:55: undefined: unix.ENOTCONN

**Comment by li-jin-gou** [comment]
already fix and use 0.5.1 version
