### ISSUE TITLE
生成的代码提示“Not enough arguments in call to ***”

### ISSUE THREAD

**Issue by Demonwuwen** [cloudwego/cloudwego.github.io#514]
七千多行代码，一半提示这个错误，因为生成的接口方法中多了context参数，不知如何解决，一个一个删太慢了

**Comment by Demonwuwen** [comment]
已解决，自己读文档不够认真。
FAQ中：
Q6: 出现 Thrift 接口编译问题，如 not enough arguments in call to iprot.ReadStructBegin

Kitex 依赖 Thrift v0.13，因为Apache Thrift v0.14 接口有 breaking change，无法直接升级。出现该问题是拉到了新版本的 Thrift，升级版本时建议不使用 -u 参数，可以执行命令固定版本 go mod edit -replace [github.com/apache/thrift=github.com/apache/thrift@v0.13.0](mailto:github.com/apache/thrift=github.com/apache/thrift@v0.13.0)

**Comment by li-jin-gou** [comment]
下个版本会在 kitex 工具生成的 mod 文件中固定 thrift 版本😀
