### ISSUE TITLE
熔断器使用说明有误?

### ISSUE THREAD

**Issue by wpc0086** [cloudwego/cloudwego.github.io#538]
https://www.cloudwego.io/zh/docs/kitex/tutorials/basic-feature/circuitbreaker/#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B

官网说默认提供的是 circuitbreaker.RPCInfo2Key，但是实际上是circuitbreak.RPCInfo2Key。并没有er

```
// build a new CBSuite
	cbs := circuitbreak.NewCBSuite(circuitbreak.RPCInfo2Key)
	c, err := userservice.NewClient(
		consts.UserServiceName,
		client.WithCircuitBreaker(cbs),
		client.WithResolver(r),
		client.WithMiddleware(mw.CommonMiddleware),
		client.WithInstanceMW(mw.ClientMiddleware),
		client.WithClientBasicInfo(&rpcinfo.EndpointBasicInfo{ServiceName: consts.ApiServiceName}),
	)
```

**Comment by GuangmingLuo** [comment]
是的，这里有个错误，你愿意提交一个 PR 修复下吗？@wpc0086

**Comment by wpc0086** [comment]
> 是的，这里有个错误，你愿意提交一个 PR 修复下吗？@wpc0086

已经PR了，不知道可不可以？ @GuangmingLuo

**Comment by GuangmingLuo** [comment]
这里跟进：https://github.com/cloudwego/cloudwego.github.io/pull/539
