### ISSUE TITLE
hz 使用 (thrift)跟着文档操作生成的代码函数调用参数不足

### ISSUE THREAD

**Issue by Nihilism0** [cloudwego/cloudwego.github.io#561]
![截屏2023-03-03 08 43 19](https://user-images.githubusercontent.com/114405451/222607025-f7fb3761-dc8d-4121-b8e3-170038276ab4.png)

即使我不加module option一样会生成图片一样的代码

hz 版本
hz version v0.6.1

系统：macOS

go env：
nihilism@NihilismdeMacBook-Pro awesomeProject %  go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/nihilism/Library/Caches/go-build"
GOENV="/Users/nihilism/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nihilism/sdk/go1.20.1/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nihilism/sdk/go1.20.1:/Users/nihilism/sdk/go1.20.1/bin"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/nihilism/sdk/go1.20.1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/nihilism/sdk/go1.20.1/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/nihilism/GolandProjects/awesomeProject/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hp/k_nbwpfd0813gzgswbrz0h5m0000gn/

**Comment by rogerogers** [comment]
没太明白，module参数不是加了吗，你这好像不是按照步骤运行的，步骤里没有一开始的`go mod init`

**Comment by Nihilism0** [comment]
是的，解决了，最开始的go.mod没有 replace github.com/apache/thrift => github.com/apache/thrift v0.13.0
