### ISSUE TITLE
为什么没有proto的生成示例

### ISSUE THREAD

**Issue by yupor5** [cloudwego/cloudwego.github.io#604]
为什么没有proto的生成示例

**Comment by li-jin-gou** [comment]
提issue建议详细描述一下，光这一句话完全不知道是哪个项目的哪节文档。。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月12日(周三) 晚上9:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cloudwego/cloudwego.github.io] 为什么没有proto的生成示例 (Issue #604)




 
为什么没有proto的生成示例
