### ISSUE TITLE
Optimise(docs): Improving Hertz's stream documentation

### ISSUE THREAD

**Issue by cachehitio** [cloudwego/cloudwego.github.io#606]
**Is your feature request related to a problem? Please describe.**

This issue is part of [Hertz Recipes](https://bytedance.feishu.cn/docx/doxcn7SedWQ69Hw9RcoJmaKIdoe), a purposal to improve documentation quality for Hertz's functionalities

I opened this issue to investigate and keep track of answers of the following problem:
1. What are docs of other go http frameworks?
2. Which topic is covered in their docs and to which extent the topics have been discussed?
3. What's missing in Hertz's doc?
4. How should the doc be organised (the layout)?

Upon agreement of the community with regards to the question above, we should be finalised the documentation in both Chinese and English.

**Comment by li-jin-gou** [comment]
@Haswf  any progress ?

**Comment by Haswf** [comment]
> @Haswf any progress ?

Thank you for your remainder. I was suffering from myofascial pain syndrome (a.k.a 肌筋膜炎) this month, and was instructed to reduce sitting time. I will try to follow up this issue after a full recovery.

**Comment by li-jin-gou** [comment]
> > @Haswf any progress ?
> 
> Thank you for your remainder. I was suffering from myofascial pain syndrome (a.k.a 肌筋膜炎) this month, and was instructed to reduce sitting time. I will try to follow up this issue after a full recovery.

thanks

**Comment by li-jin-gou** [comment]
any process ?

**Comment by chaoranz758** [comment]
can i try it ?
