### ISSUE TITLE
Hertz

### ISSUE THREAD

**Issue by maojinhua** [cloudwego/cloudwego.github.io#614]
如何删除接口？
比如说我一开始写了一个
hello.proto这个接口描述的 idl ，后续我把这个 hello.proto 文件删除了，对应的里面的接口要怎么删除呢？只能手动去删除 router 文件吗？ 还是 hz 有什么选项可以自动删除 router 里对应的代码呢

**Comment by li-jin-gou** [comment]
make a issue to https://github.com/cloudwego/hertz/issues
