### ISSUE TITLE
快速开始

### ISSUE THREAD

**Issue by maojinhua** [cloudwego/cloudwego.github.io#616]
生成代码 hz new 这个命令错了
要用 hz new -module 模块名才可以，最好把文档更新一下，否则新手第一次用就不能生成，挺影响体验的
![image](https://user-images.githubusercontent.com/13777695/233017371-82fd6555-81e5-4601-8f89-0b6cb8547316.png)

**Comment by GuangmingLuo** [comment]
@li-jin-gou pls help with this
