### ISSUE TITLE
IDL 注解说明

### ISSUE THREAD

**Issue by maojinhua** [cloudwego/cloudwego.github.io#630]
返回值格式不能支持注解吗？
比如说 {Resp:"aa"} 我想要返回的是 {resp:"aa"}

**Comment by li-jin-gou** [comment]
参考 https://stackoverflow.com/questions/31319534/control-golang-annotations-in-thrift-generated-code ，注入 go tag  使用 json 注解。

**Comment by maojinhua** [comment]
我使用的是 proto 要怎么弄呢？如果想一个字段必须传递 tag 是什么呢~

**Comment by li-jin-gou** [comment]
这个地方可以参考上文链接，使用搜索引擎搜索一下 PB 的用法即可。

**Comment by maojinhua** [comment]
> 

嗯好的谢谢
