### ISSUE TITLE
hz 使用 (protobuf)

### ISSUE THREAD

**Issue by maojinhua** [cloudwego/cloudwego.github.io#631]
请问如何生成必须传输的请求字段呢？我看通过protobuf 生成的 字段都是 omitempty,有必传的字段要怎么写 呢？

比如 我下面的 id 和 name 字段要求必传，要怎么写 UpdateRepositoryReq 呢？
message UpdateRepositoryReq {
  int64 Id = 1[(api.path) = "id"];
  string Name = 2[(api.body) = "name"];
}

type UpdateRepositoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" path:"id"`
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" form:"name" json:"name,omitempty"`
}

**Comment by maojinhua** [comment]
这样子写吗？
message UpdateRepositoryReq {
int64 Id = 1[(api.path) = "id,required"];
string Name = 2[(api.body) = "name,required"];
}

**Comment by rogerogers** [comment]
https://www.cloudwego.io/docs/hertz/tutorials/toolkit/usage/command/

如果所有字段都是required的话`hz --unset_omitempty`
部分字段的话要自己判断

**Comment by maojinhua** [comment]
> https://www.cloudwego.io/docs/hertz/tutorials/toolkit/usage/command/
> 
> 如果所有字段都是required的话`hz --unset_omitempty` 部分字段的话要自己判断

你好 自己要怎么判断呢？

**Comment by rogerogers** [comment]
https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/binding-and-validate/
建议先看下文档的相关部分。

**Comment by maojinhua** [comment]
> hz --unset_omitempty

嗯好的谢谢

**Comment by maojinhua** [comment]
> https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/binding-and-validate/ 建议先看下文档的相关部分。

你好 我试了，这样子写就可以
message UpdateRepositoryReq {
int64 Id = 1[(api.path) = "id,required"];
string Name = 2[(api.body) = "name,required"];
}
