### ISSUE TITLE
优化 Cache 文档可配置项展示方式

### ISSUE THREAD

**Issue by welkeyever** [cloudwego/cloudwego.github.io#649]
from lilinyi

我觉得目前文档写的不合理 希望如下修改 （我第一次看觉得是这些属性都是可以用的 发现有的是某一些情况可以用）
目前 
![img_v2_196cd95a-8af1-4bc1-944e-af55b54916cg](https://github.com/cloudwego/cloudwego.github.io/assets/9826697/a1706167-4ad3-4b45-8ff6-241e7c466b89)

希望
通用配置
WithOnHitCache nil 用于设置缓存命中的回调函数
WithOnMissCache nil 用于设置缓存未命中的回调函数

各模式自己的额外配置
NewCache 模式
WithCacheStrategyByRequest	nil	用于设置自定义的缓存策略

NewCacheByRequestURI 模式
WithIgnoreQueryOrder false	用于设置当使用 URI 为缓存的 Key 时，忽略 query 参数的顺序

**Comment by Hanser001** [comment]
Please give it to me👋

**Comment by rogerogers** [comment]
> Please give it to mewave

Thank you
