### ISSUE TITLE
按照你的的步骤执行到hz new，生成的目录中没有go.mod这个文件并且还是提示一个错误

### ISSUE THREAD

**Issue by xl9612** [cloudwego/cloudwego.github.io#658]
do not generate 'go.mod', please add 'replace github.com/apache/thrift => github.com/apache/thrift v0.13.0' to your 'go.mod'

**Comment by rogerogers** [comment]
这个提示是项目已经存在go.mod文件

麻烦提供下
- 参考文档链接
- 操作系统
- 命令工具版本信息
`hz --version`
- 当前目录结构
`ls`(linux) or `dir`(windows)
- 具体执行命令

**Comment by li-jin-gou** [comment]
这不是一个错误，而是一个提示 默认不生成 go.mod 了 @xl9612

**Comment by FGYFFFF** [comment]
你可以在生成代码的时候指定一个”module“，这样工具会自动为你添加 go.mod，例如`hz new --mod=github.com/hertz/text`
