### ISSUE TITLE
Lack of explanation of what BackupRetry and TimeoutRetry is

### ISSUE THREAD

**Issue by delabania** [cloudwego/cloudwego.github.io#68]
There is no information in what type of failure triggers BackupRetry (TimeoutRetry is pretty obvious) in documenataion: https://www.cloudwego.io/docs/tutorials/basic-feature/retry/

**Comment by YangruiEmma** [comment]
BackupRetry is not triggered by failure. If the response doesn't receive within a delay duration then the retry request will be sent.
