### ISSUE TITLE
快速开始

### ISSUE THREAD

**Issue by Milkve** [cloudwego/cloudwego.github.io#682]
**What needs to be changed?**

![image](https://github.com/cloudwego/cloudwego.github.io/assets/45092129/9c55ed5e-b7f5-4704-a530-8cc5eebb26ad)

如图，[这里](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/usage/) 这个链接里给出的生成代码的命令里使用的关键字是 `-mod` 和本页面上写出的 `-module` 不一致。

本页上面提到的 `go mod init` 是多余的，如果之前按照”这里“链接里 `hz new -mod hertz/demo` 执行完以后，`go.mod` 文件已经存在了

**What is the name + path of the page that needs changed?**

[生成/编写示例代码](https://www.cloudwego.io/zh/docs/hertz/getting-started/#%E7%94%9F%E6%88%90%E7%BC%96%E5%86%99%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81) 里面生成代码的步骤和 [new: 创建一个 Hertz 新项目](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/usage/#new-%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA-hertz-%E6%96%B0%E9%A1%B9%E7%9B%AE) 里的步骤有出入。

**Comment by li-jin-gou** [comment]
感谢反馈

**Comment by li-jin-gou** [comment]
暂时将这个设置为新手任务，如果没有人认领，我抽个时间修复一下。

**Comment by Milkve** [comment]
那我来吧，直接 pr 然后关联到这里吗

**Comment by li-jin-gou** [comment]
> 那我来吧，直接 pr 然后关联到这里吗

可以

**Comment by rogerogers** [comment]
这个应该是要修改下描述

- GOPATH 下执行不会生成 go.mod，是需要go mod init这一步的
- 非GOPATH下执行需要指定-mod或者-module，不需要执行go mod init这一步

我试了下暂时应该还是这样的，cwgo在哪里都会生成go.mod貌似。

**Comment by li-jin-gou** [comment]
> 这个应该是要修改下描述
> 
> * GOPATH 下执行不会生成 go.mod，是需要go mod init这一步的
> * 非GOPATH下执行需要指定-mod或者-module，不需要执行go mod init这一步
> 
> 我试了下暂时应该还是这样的，cwgo在哪里都会生成go.mod貌似。

最新的 hz 是的。

**Comment by Milkve** [comment]
[生成/编写示例代码](https://www.cloudwego.io/zh/docs/hertz/getting-started/#%E7%94%9F%E6%88%90%E7%BC%96%E5%86%99%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81) 中文页面里的代码块语言没选 Go，然后我看我涉及到的这四个页面里终端命令的代码块是一会 console 一会 bash，有些地方可能之前的大佬们敲得太快空格丢了，这些需要改吗？

**Comment by li-jin-gou** [comment]
> [生成/编写示例代码](https://www.cloudwego.io/zh/docs/hertz/getting-started/#%E7%94%9F%E6%88%90%E7%BC%96%E5%86%99%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81) 中文页面里的代码块语言没选 Go，然后我看我涉及到的这四个页面里终端命令的代码块是一会 console 一会 bash，有些地方可能之前的大佬们敲得太快空格丢了，这些需要改吗？

可以统一，感谢。

**Comment by Milkve** [comment]
> > [生成/编写示例代码](https://www.cloudwego.io/zh/docs/hertz/getting-started/#%E7%94%9F%E6%88%90%E7%BC%96%E5%86%99%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81) 中文页面里的代码块语言没选 Go，然后我看我涉及到的这四个页面里终端命令的代码块是一会 console 一会 bash，有些地方可能之前的大佬们敲得太快空格丢了，这些需要改吗？
> 
> 可以统一，感谢。

我改好了，大佬明早看到帮忙审一下
