### ISSUE TITLE
元信息传递扩展

### ISSUE THREAD

**Issue by yuxn** [cloudwego/cloudwego.github.io#702]
windows11 元信息传递 拿不到数据

hz 转发请求后：  KITEX: processing request error, remoteService=, remoteAddr=127.0.0.1:62750, error=default codec read failed: read tcp 127.0.0.1:8006->127.0.0.1:62750: i/o timeout

**Comment by li-jin-gou** [comment]
参考 example https://github.com/cloudwego/kitex-examples/tree/main/metainfo
