### ISSUE TITLE
文档建议

### ISSUE THREAD

**Issue by YingHYingH** [cloudwego/cloudwego.github.io#703]
请求重试这篇文档中

使用方式
代码配置开启
注意：若通过代码配置开启重试，动态配置 (见 3.3) 则无法生效。

这个3.3具体指的是什么，全文貌似没有采用这样的结构化命名

**Comment by felix021** [comment]
抱歉，这是「动态配置」是字节跳动内部的能力，这部分从内部文档搬运到官网时没有删掉，我稍后更新一下。

**Comment by felix021** [comment]
官网文档已更新。
