### ISSUE TITLE
微信群怎么加不了，有问题去哪里问

### ISSUE THREAD

**Issue by hyyky** [cloudwego/cloudwego.github.io#726]
微信群怎么加不了，有问题去哪里问
![image](https://github.com/cloudwego/cloudwego.github.io/assets/50724513/b8fee3cd-007a-4990-bb27-95aa2433c99e)

**Comment by li-jin-gou** [comment]
有问题可以先看文档，实在解决不了可以仓库下提 issue，会有同学定时回复。
