### ISSUE TITLE
HTTP2

### ISSUE THREAD

**Issue by Tom-debug110** [cloudwego/cloudwego.github.io#734]
一个小问题,今天打算用hertz 做一个 http 的实验的时候,发现的,应该是Mac 上的一个小小的输入错误,按住 Option 键啦

<img width="1406" alt="image" src="https://github.com/cloudwego/cloudwego.github.io/assets/70630606/d2301a4a-d56e-44ec-b94a-9e5023f52412">

**Comment by rogerogers** [comment]
感谢反馈，也欢迎pr修正😄

**Comment by Tom-debug110** [comment]
好滴呢,一会就提上去啦
