### ISSUE TITLE
Swag init 版本兼容性问题

### ISSUE THREAD

**Issue by xuanskyer** [cloudwego/cloudwego.github.io#739]
现在 默认的 swag 安装版本是1.8.12 ，swag init 生成的 的SwaggerInfo 如下：
```
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "HertzTest",
	Description:      "This is a demo using Hertz.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}
```
其中的 `LeftDelim` 和 `RightDelim` 对应的默认版本的 github.com/hertz-contrib/swagger 不支持，要用swag 的 1.8.11及以下版本 swag init 出来的才是兼容的

**Comment by GuangmingLuo** [comment]
refer to: https://github.com/hertz-contrib/swagger/issues/6

**Comment by GuangmingLuo** [comment]
update to https://github.com/hertz-contrib/swagger/releases/tag/v0.1.0
