### ISSUE TITLE
「消息协议和传输协议」文档描述反馈

### ISSUE THREAD

**Issue by max123ios** [cloudwego/cloudwego.github.io#749]
我觉得解释对小白非常不友好，前面从来没说消息协议，只有消息类型和序列化方式还有传输协议，这里突然提到消息协议，在消息类型那里有一个表格说gRPC是传输协议，这里就突然变成消息协议，总之小白会被绕进去。

**Comment by GuangmingLuo** [comment]
@YangruiEmma PTAL

**Comment by YangruiEmma** [comment]
不知道你指的是哪个文档，消息协议和传输协议的关系在概览页有简单介绍
https://www.cloudwego.io/zh/docs/kitex/overview/#%E6%A1%86%E6%9E%B6%E7%89%B9%E7%82%B9

> RPC 消息协议默认支持 Thrift、Kitex Protobuf、gRPC
> 传输协议封装消息协议进行 RPC 互通

序列化协议单纯是指序列化，pb和Thrift都可以单独用于结构体的序列化，rpc通信需要消息协议来定义 RPC 请求，pb 没有 RPC 消息协议的定义，Thrift 有。

**Comment by YangruiEmma** [comment]
no reply for this issue.
