### ISSUE TITLE
希望能够指定kitex生成脚手架的位置

### ISSUE THREAD

**Issue by SIN5t** [cloudwego/cloudwego.github.io#764]
每次生成代码之后都需要将生成的脚手架handler之类的文件移动到指定文件夹，感觉不太方便。如果可以的话，能出一个像mybatisX这样的插件，直接图像界面选择gen生成的文件夹位置，脚手架生成的位置，而且如果能做到像gorm思想一样，修改idl。再生成一次代码，会自动更新gen文件就更好了

**Comment by HeyJavaBean** [comment]
做图像界面的工作量有点大.....
不过目前对脚手架的自定义这块确实还有点欠缺。目前我们有自己写模板，配置生成目录的功能，可以看下这个：https://www.cloudwego.io/zh/docs/kitex/tutorials/code-gen/custom_tpl/

**Comment by SIN5t** [comment]
感谢，这就是我想要的
