### ISSUE TITLE
直连样例不完整， 直连cli 是哪个包呀？

### ISSUE THREAD

**Issue by chenxiang105** [cloudwego/cloudwego.github.io#771]
import "github.com/cloudwego/kitex/client/callopt"
...
resp, err := cli.Echo(context.Background(), req, callopt.WithHostPort("127.0.0.1:8888"))
if err != nil {
   log.Fatal(err)
}

**Comment by rogerogers** [comment]
https://github.com/cloudwego/kitex-examples/blob/ffcf367ca84dcc24f3a5b77edbbbd7483e89814c/retry/client/backup/main.go#L33C1-L33C1
参考下kitex-example
