### ISSUE TITLE
Part 3. 编写 Client 端

### ISSUE THREAD

**Issue by Wtbg** [cloudwego/cloudwego.github.io#776]
**与默认生成的server.rs配合的不是很好**
使用机器为win10，按照文档quick start中使用volo遇到两个问题
1. 在我的机器上需要使用nightly版本才能install volo-cli但是文档貌似没有提及
2. 在server.rs中main函数如下
let addr: SocketAddr = "[::]:8080".parse().unwrap();
文档中的client.rs中的lazy_static变量中则为let addr: SocketAddr = "127.0.0.1:8080".parse().unwrap();
在运行后OS产生Error：由于目标计算机积极拒绝，无法连接
修改server.rs中地址为127.0.0.1:8080后问题解除
原理不是非常理解，但是问题可以稳定浮现

**Comment by PureWhiteWu** [comment]
你好，针对问题 1，你是使用的 volo-cli 来初始化项目的么？volo-cli 会默认加上 nightly 的 rust-toolchain.yml 文件。
针对问题 2，怀疑可能是 win10 默认没有监听双栈，行为和 linux 不太一致导致的，这个我们后面看看有没有办法在 windows 上也监听双栈。
另外，是否有 win11 机器能够帮忙确认一下 win11 上的行为呀？感谢。

**Comment by Wtbg** [comment]
您好，感谢您的回复
关于问题1，您好像没理解正确，我的意思是运行`cargo install volo-cli`时需要使用rustup default nightly或类似命令切换为nightly，否则编译会不通过，该问题在另一台win10主机上表现相同，应当不是偶发问题，不过切换回stable重新用--force的方式install没能复现报错，遗憾没能保存报错截图
抱歉没有可用的win11机器

**Comment by PureWhiteWu** [comment]
好的，感谢反馈，不过 volo-cli 在设计中应当是不需要 nightly 的，这个我们后续确认一下。

**Comment by NightSkyZHX** [comment]
在win11上出现了同样的两个问题

**Comment by PureWhiteWu** [comment]
感谢反馈，看起来 Windows 的行为和预期不太一致，已经在新的文档中修复，默认使用 ipv6 loopback。
