### ISSUE TITLE
kitex 的Client 通过context.withValue 写入kv， 在Server的handler中，context.value无法读取到

### ISSUE THREAD

**Issue by chenxiang105** [cloudwego/cloudwego.github.io#782]
1. The client side is generated through kitex, and some of the meta information of http will be written to the context at the API layer
2. The context value is normal before the RPC call
3. Call to the rpc service, check the context in the handler without any value

Service discovery tested: ETCD, code generation: kitex proto file

Test the value transmission method:
1. client. WithMetaHandler(meta_handler. ClientTTHeaderHandler)    ： 测试不通过，Server端取值为空
2. rpc Client前
       2.1  ctx = metadata.AppendToOutgoingContext(ctx, "X_REQUEST_ID", "1232142131312")  : 测试不通过
       2.2 metainfo.WithValue(ctx, "X_REQUEST_ID", "1232142131312")  : 测试不通过
     2.3 context.WithValue(ctx, "X_REQUEST_ID", "1232142131312")   : 测试不通过
    Server:
       md, ok := metadata.FromIncomingContext(ctx)
       (md.Get("X_REQUEST_ID")
       
      logId, ok := ctx.Value("X_REQUEST_ID").(string)

**Comment by felix021** [comment]
Please update to the newest version of Kitex and follow the instructions in this doc:

https://www.cloudwego.io/zh/docs/kitex/tutorials/advanced-feature/metainfo/

**Comment by chenxiang105** [comment]
follow an example in the document: https://www.cloudwego.io/zh/docs/kitex/tutorials/advanced-feature/metainfo/ 
in client: 
 metainfo.WithPersistentValue(ctx, "X_REQUEST_ID", "111111")
 
 in server:
 values := metainfo.GetAllPersistentValues(ctx)

print values is nil

**Comment by chenxiang105** [comment]
How to check the context values  is marshaled  in client  and unmarshaled in server?

**Comment by chenxiang105** [comment]
bug: 
metainfo.WithPersistentValue(ctx, "X_REQUEST_ID", "111111")

fix: 
ctx = metainfo.WithPersistentValue(ctx, "X_REQUEST_ID", "111111")

its work now !
