### ISSUE TITLE
文档中有一部分有点让人迷惑

### ISSUE THREAD

**Issue by Mutezebra** [cloudwego/cloudwego.github.io#802]
https://www.cloudwego.io/zh/docs/hertz/tutorials/framework-exten/response_writer/  中ChunkedBodyWriter的实例代码部分其目的应该是不断地刷新分块吧，但是我使用postman或者浏览器在本地测试的结果都是一次性输出所有的结果，而非每flush一次就输出一部分结果。

**Comment by chaoranz758** [comment]
把实例中的 i 调大一些，例如100应该在浏览器中就可以看到效果了，postman 应该是看不到不断刷新的效果的

**Comment by Mutezebra** [comment]
经过测试已经可以满足需求了。只是好像当flush达到一定次数之后，接下里的flush才能看到不断刷新的效果。我粗略的测试下这个次数的大小大概在22次左右，并且似乎与flush数据的大小无关，而与次数有关。(没有严格测试，只是根据个人需求简单的测试得出的推论)

**Comment by li-jin-gou** [comment]
> 经过测试已经可以满足需求了。只是好像当flush达到一定次数之后，接下里的flush才能看到不断刷新的效果。我粗略的测试下这个次数的大小大概在22次左右，并且似乎与flush数据的大小无关，而与次数有关。(没有严格测试，只是根据个人需求简单的测试得出的推论)

代码:
```
package main

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/http1/resp"
	"strings"
	"time"
)

func main() {
	h := server.Default()
	h.GET("/flush/chunk", func(c context.Context, ctx *app.RequestContext) {
		// Hijack the writer of Response
		ctx.Response.HijackWriter(resp.NewChunkedBodyWriter(&ctx.Response, ctx.GetWriter()))

		for i := 0; i < 10; i++ {
			ctx.Write([]byte(fmt.Sprintf("chunk %d: %s \n", i, strings.Repeat("hi~", i)))) // nolint: errcheck
			ctx.Flush()                                                                    // nolint: errcheck
			time.Sleep(1 * time.Second)
		}
	})
	h.Spin()
}

```
 curl: 
```
curl -N --location 'localhost:8888//flush/chunk'
```
![image](https://github.com/cloudwego/cloudwego.github.io/assets/97824201/209cb10d-3071-41ee-af12-5419cef6758f)

验证无问题，可以体验试一下，这个 chunk 方式内部核心业务在用的，不会有问题的。
