### ISSUE TITLE
生成引用结构体

### ISSUE THREAD

**Issue by qingyggg** [cloudwego/cloudwego.github.io#821]
我尝试了一下，在github新建里仓库，叫qingyggg/gotest,然后初始化里echo.thrift并且提交推送上去了
然后自己本地又新建里，并且招呼画瓢
idl-ref.yml:
` ref:
  idl/echo.thrift:  "github.com/qingyggg/gotest"`
然后在终端里敲了`kitex -module example -service example-server echo.thrift`
生成了但是结果没有文档所写的‘’生成产物的一个例子’’那样子，跟不写idl.yml生成出来的没有区别

**Comment by HeyJavaBean** [comment]
外部文档没来得及更新，当 thriftgo 版本高于 v0.3.0 之后，额外带上 -thrift code_ref 参数，例如：
kitex -module example -service example-server -thrift code_ref echo.thrift
生成的产物会叫 xx-ref.go，里面就是引用的实现代码

**Comment by qingyggg** [comment]
好的，已经解决了谢谢

**Comment by GuangmingLuo** [comment]
文档更新后再来 close 这个 issue 吧 @HeyJavaBean
