### ISSUE TITLE
Drop `$` symbol for more convenient copy paste experience.

### ISSUE THREAD

**Issue by meowjesty** [cloudwego/cloudwego.github.io#851]
**What needs to be changed?** Describe the update that is required.

The docs use `$` to indicate that this is a shell command, but when you click on the _Copy_ button, the `$` symbol also gets copied.

What do you think of removing these symbols from the docs and making copy paste easier?

I would also suggest either breaking individual commands into separate code blocks, or having the block contain all the actions in a way that copy paste just works, like `mkdir volo-example && cd volo-example && ...`

**What is the name + path of the page that needs changed?** The relative path
and page title where you found a problem.

Creating this issue for https://www.cloudwego.io/docs/volo/volo-grpc/getting-started/part_2/ but other command examples also have this inconvenience.

**Comment by GuangmingLuo** [comment]
Thanks for the feedback and suggestion. We will optimize all the code blocks.
