### ISSUE TITLE
代码生成工具

### ISSUE THREAD

**Issue by wheelergeo** [cloudwego/cloudwego.github.io#909]
kitex使用自定义模版生成脚手架，没有指定serviceName的入口，导致用模版生成的代码是没有serviceName的

**Comment by li-jin-gou** [comment]
![image](https://github.com/cloudwego/cloudwego.github.io/assets/97824201/00407c5c-4ff9-43ab-9ee7-e6fad4799889)
![image](https://github.com/cloudwego/cloudwego.github.io/assets/97824201/b7eae7df-ffa4-4a0c-812f-3f1342e8422e)

本地验证无问题

**Comment by li-jin-gou** [comment]
cc @ViolaPioggia  完善一下 template 的 example 吧

**Comment by wheelergeo** [comment]
> cc @ViolaPioggia 完善一下 template 的 example 吧

kitex v0.7.1参数指定了-service，就无法指定-template-dir
-template-dir and -service cannot be specified at the same time

**Comment by li-jin-gou** [comment]
> > cc @ViolaPioggia 完善一下 template 的 example 吧
> 
> kitex v0.7.1参数指定了-service，就无法指定-template-dir -template-dir and -service cannot be specified at the same time

cwgo 没有这个限制，可以先用 cwgo

**Comment by li-jin-gou** [comment]
看起来这是 kitex 的 feat，但是用户该如何指定 service_name 😨  @HeyJavaBean

**Comment by wheelergeo** [comment]
> > > cc @ViolaPioggia 完善一下 template 的 example 吧
> > 
> > 
> > kitex v0.7.1参数指定了-service，就无法指定-template-dir -template-dir and -service cannot be specified at the same time
> 
> cwgo 没有这个限制，可以先用 cwgo

但是cwgo没办法指定已生成的kitex_gen，或是kitex_gen生成的目标目录

**Comment by li-jin-gou** [comment]
cwgo 可以通过 -pass 参数传递 kitex 的参数

**Comment by li-jin-gou** [comment]
> cwgo 可以通过 -pass 参数传递 kitex 的参数

cc @chaoranz758 帮忙确定下，应该是可以的

**Comment by chaoranz758** [comment]
指定已生成的 kitex_gen：cwgo server -service {your service name} -module {your service module} -type rpc -pass "-use {your exist kitex_gen path}" -idl {your idl path}
更改生成的目标目录：kitex_gen：cwgo server -service {your service name} -module {your service module} -type rpc -pass "-gen-path {new kitex_gen path}" -idl {your idl path}

**Comment by li-jin-gou** [comment]
> 指定已生成的 kitex_gen：cwgo server -service {your service name} -module {your service module} -type rpc -pass "-use {your exist kitex_gen path}" -idl {your idl path} 更改生成的目标目录：kitex_gen：cwgo server -service {your service name} -module {your service module} -type rpc -pass "-gen-path {new kitex_gen path}" -idl {your idl path} cwgo 是支持的 @wheelergeo

thanks @chaoranz758
