### ISSUE TITLE
【建议】说明文档后面，能否增加上一章/下一章链接，目前看完还得回到前面的目录，比较麻烦

### ISSUE THREAD

**Issue by RickyWangGithub** [cloudwego/cloudwego.github.io#910]
<img width="754" alt="image" src="https://github.com/cloudwego/cloudwego.github.io/assets/7765174/289b6854-38ef-48ab-bd80-e165fc55ef20">
https://www.cloudwego.io/zh/docs/kitex/getting-started/

**Comment by li-jin-gou** [comment]
得看现在用的这个项目支持否，就跟楼下夜间模式一样

**Comment by RickyWangGithub** [comment]
没正面回复问题呀，那辛苦看下当前的项目是否支持，难道字节节奏是这样的。（不过还是为及时回复点赞👍）

**Comment by li-jin-gou** [comment]
我也不知道能不能搞，等了解的同学回复吧

**Comment by GuangmingLuo** [comment]
通过电脑端查看项目文档，如果需要查看其它文档页面，可以通过点击左侧导航目录进行切换。
不同于「blog」页面，其所有博客都是平级支持上下切页，「doc」全局没有上下页之分。

**Comment by rogerogers** [comment]
这个暂时不支持，项目本身依赖于 docsy，docsy 对于这个功能后续有支持规划 https://github.com/google/docsy/milestone/10
