### ISSUE TITLE
Document search don't work in some cases

### ISSUE THREAD

**Issue by a631807682** [cloudwego/cloudwego.github.io#912]
**What happened?** Describe the problem that occurred.

I cannot search the Multiple Services document of kitex through the keyword multiple

**What did you expect would happen?** Describe the expected result/output.

![b88d272d-a81b-4ece-bf8d-3e568177be10](https://github.com/cloudwego/cloudwego.github.io/assets/11827916/7a14fe8e-f78c-4c53-9acc-2c491f6329a0)

https://www.cloudwego.io/docs/kitex/tutorials/advanced-feature/multi_service/

**What is the name + path of the page where you encountered the issue?** The
relative path and page title where you found a problem.

**What browser, OS, and platform were you using when you encountered the
problem?** Include the browser version if you know it as well.

**Additional context**: anything else you can think about that would be helpful.

_Please delete paragraphs that you did not use before submitting._

**Comment by rogerogers** [comment]
works now.
