### ISSUE TITLE
example code error

### ISSUE THREAD

**Issue by yicixin** [cloudwego/cloudwego.github.io#914]
**What needs to be changed?** 
app.handlerFunc => app.HandlerFunc
hlog.Ingo => hlog.Info

**What is the name + path of the page that needs changed?** 
/docs/hertz/tutorials/basic-feature/engine/#use

**Comment by li-jin-gou** [comment]
cc @chaoranz758

**Comment by chaoranz758** [comment]
Thanks for your feedback, i will make the changes later.
