### ISSUE TITLE
如何在一个项目中使用rpc和http服务

### ISSUE THREAD

**Issue by zengxiaolou** [cloudwego/cloudwego.github.io#962]
我现在需要写一个单点登录的服务，既要被http服务访问，又要在集群中被其他服务使用rpc访问。这种情况下该如何使用hertz和ketix呢？
https://github.com/cloudwego/hertz-examples/tree/main/hz_kitex_demo
看了这个demo有些疑问：

 分别使用hertz和ketix根据idl生成对应的服务、还有client客户端，共用同一套service层，在完成开发后，提交代码到gitlab仓库中，通过tag，在其他项目中使用。这个依赖中包含了http和rpc的服务端，是不是有点问题，引入了无用的代码

**Comment by li-jin-gou** [comment]
参考 https://github.com/cloudwego/hertz-examples/tree/main/hex
