### ISSUE TITLE
命令行工具

### ISSUE THREAD

**Issue by flairamos** [cloudwego/cloudwego.github.io#975]
question:  "flag provided but not defined: -out_dir"

i use the cwgo command to generate the standard code, there is not `--out_fir` command on cwgo with version `v0.0.0-20240103024320-203b523ed461`

like this :
![image](https://github.com/cloudwego/cloudwego.github.io/assets/125383416/72ecb74a-4700-45d3-a247-51b90d91b037)

**Comment by li-jin-gou** [comment]
This parameter has been removed in later versions.

**Comment by li-jin-gou** [comment]
cc @chaoranz758
